### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by evilvenom** [EBI-Metagenomics/emgapi#239]
Even though the repo contains the Dockerfile, the docker-compose using docker-compose.yml (at https://github.com/EBI-Metagenomics/mgnify-web) errors as ERROR: Cannot locate specified Dockerfile: docker/Dockerfile

Please help me with this regards.

Thanks in advance!

**Comment by SandyRogers** [comment]
Hi there @evilvenom .
Were you following the Docker Compose setup instructions from the MGnify Web repository? I've just pushed [a commit](https://github.com/EBI-Metagenomics/mgnify-web/commit/78544c3b9cf25cb1bd294b7eaf8f426823b06c22) over there, now on `master`, to point the submodules (including this EMG-API) at the latest versions. If you're using MGnify Web, you can always [update the submodules to the latest versions using Git](https://stackoverflow.com/a/1032653)

Thanks!

**Comment by evilvenom** [comment]
Thank you for the response!
