### ISSUE TITLE
SQL database

### ISSUE THREAD

**Issue by evilvenom** [EBI-Metagenomics/emgapi#240]
While creating databases using mysql from where do I get the database files like `travis/biomes.sql` as mentioned in the study?

**Comment by SandyRogers** [comment]
Hi there @evilvenom. 
If you use the parent repo [MGnify Web](https://github.com/EBI-Metagenomics/mgnify-web), then the [Makefile](https://github.com/EBI-Metagenomics/mgnify-web/blob/master/Makefile) includes commands for creating these test databases, as well as the test data themselves within the frontend submodules (`ebi-metagenomics-webkit` and `ebi-metagenomics-frontend`).

**Comment by evilvenom** [comment]
Thanks sir!
