### ISSUE TITLE
Can I run my samples from API metagenomics pipeline?

### ISSUE THREAD

**Issue by evilvenom** [EBI-Metagenomics/emgapi#245]
How do I run some amplicon sequence files that I have on my local system using the metagenomics pipeline of MGnify API?

**Comment by caballero** [comment]
Hi, unfortunately, the API is for retrieving analysis data and metadata, there is no option to upload and create new analysis jobs, however, data can be registered and uploaded in [ENA](https://www.ebi.ac.uk/metagenomics/) for analysis.
